org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1.2
yarn_mappings=26.1.2+build.7
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.1
maven_group=com.survivalaid
archives_base_name=survival_aid

# Dependencies
fabric_api_version=0.155.2+26.1.2
carpet_version=1.4.147+v26.1.2
