org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.21.3
loader_version=0.16.0
mod_version=1.0.1
maven_group=com.survivalaid
archives_base_name=survival_aid-mc1.21.3
fabric_api_version=0.106.0+1.21.3
carpet_version=1.21.2-1.4.158+v241022
java_version=21
yarn_mappings=1.21.3+build.5
